eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://182.92.8.29:8761/eureka/
    instance:
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
        home-page-url-path: /
        ip-address: 101.200.237.82 #决定Eureka服务显示host
        hostname: ${eureka.instance.ip-address} #决定服务跳转host，必须指定
        prefer-ip-address: false #不设可自己指定，true会自动获取本地ipv4地址
        instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
feign:
  hystrix:
    enabled: true
server:
  port: 8082
spring:
    application:
        name: sport-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://182.92.8.29:3306/homework?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        open-in-view: true
        properties:
            dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
