server:
  port: 8082 #服务端口
myspcloud:
  item:
    url: http://127.0.0.1:8081/item/
###起个名字作为服务名称(该服务注册到eureka注册中心的名称，比如订单服务)
spring:
    application:
        name: sport-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://182.92.8.29:3306/homework?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
        username: root
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        open-in-view: true
        properties:
            dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
           defaultZone: http://yyt:123456@127.0.0.1:8100/eureka
###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
###是否需要从eureka上检索服务
    fetch-registry: true
  instance:
      prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
      ip-address: 127.0.0.1
      instance-id: ${spring.application.name}###${server.port} #指定实例id
diet-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#开启hystrix断路器
feign:
  hystrix:
    enabled: true
